DROP DATABASE IF EXISTS "hdx";
DROP ROLE IF EXISTS "hdx-user";
CREATE ROLE "hdxuser" LOGIN ENCRYPTED PASSWORD 'changeThis' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE DATABASE "hdx" WITH OWNER = "hdxuser" ENCODING = 'UTF8' CONNECTION LIMIT = -1;