/* entity types 
INSERT INTO text(id, default_value) VALUES (1, 'Country');
INSERT INTO entity_type(id, code, text_id) VALUES (1, 'country', 1);

INSERT INTO text(id, default_value) VALUES (2, 'Crisis');
INSERT INTO entity_type(id, code, text_id) VALUES (2, 'crisis', 2);
*/

INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'Country');
INSERT INTO entity_type(id, code, text_id) VALUES (nextval('entity_type_seq'), 'country',currval('text_seq'));
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'Crisis');
INSERT INTO entity_type(id, code, text_id) VALUES (nextval('entity_type_seq'), 'crisis',currval('text_seq'));

/* countries */
SELECT 'Starting countries' from text limit 1;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'AFGHANISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AFG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ALBANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ALB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ALGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DZA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'AMERICAN SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ASM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ANDORRA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AND', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ANGOLA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AGO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ANGUILLA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AIA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ANTARCTICA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ATA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ANTIGUA AND BARBUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ATG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ARGENTINA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ARG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ARMENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ARM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ARUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ABW', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'AUSTRALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AUS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'AUSTRIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AUT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'AZERBAIJAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'AZE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BAHAMAS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BHS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BAHRAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BHR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BANGLADESH');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BGD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BARBADOS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BRB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BELARUS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BLR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BELGIUM');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BEL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BELIZE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BLZ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BENIN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BEN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BERMUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BMU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BHUTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BTN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BOLIVIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BOL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BOSNIA AND HERZEGOWINA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BIH', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BOTSWANA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BWA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BOUVET ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BVT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BRAZIL');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BRA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IOT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BRUNEI DARUSSALAM');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BRN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BULGARIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BGR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BURKINA FASO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BFA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'BURUNDI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'BDI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CAMBODIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KHM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CAMEROON');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CMR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CANADA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CAN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CAPE VERDE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CPV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CAYMAN ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CYM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CAF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CHAD');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TCD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CHILE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CHL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CHN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CHRISTMAS ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CXR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COCOS (KEELING) ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CCK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COLOMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'COL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COMOROS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'COM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CONGO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'COG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CONGO, THE DRC');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'COD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COOK ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'COK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COSTA RICA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CRI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'COTE D''IVOIRE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CIV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CROATIA (local name: Hrvatska)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HRV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CUB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CYPRUS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CYP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'CZECH REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CZE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'DENMARK');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DNK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'DJIBOUTI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DJI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'DOMINICA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DMA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'DOMINICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DOM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'EAST TIMOR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TLS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ECUADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ECU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'EGYPT');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'EGY', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'EL SALVADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SLV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'EQUATORIAL GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GNQ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ERITREA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ERI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ESTONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'EST', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ETHIOPIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ETH ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FLK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FAROE ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FRO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FIJI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FJI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FINLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FIN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FRANCE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FRA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FRANCE, METROPOLITAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FXX', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FRENCH GUIANA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GUF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FRENCH POLYNESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PYF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ATF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GABON');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GAB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GMB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GEORGIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GEO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GERMANY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'DEU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GHANA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GHA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GIBRALTAR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GIB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GREECE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GRC', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GREENLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GRL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GRENADA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GRD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUADELOUPE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GLP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUAM');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GUM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUATEMALA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GTM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GIN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUINEA-BISSAU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GNB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'GUYANA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GUY', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HAITI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HTI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HEARD AND MC DONALD ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HMD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VAT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HONDURAS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HND', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HONG KONG');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HKG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'HUNGARY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'HUN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ICELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ISL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'INDIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IND', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'INDONESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IDN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'IRAN (ISLAMIC REPUBLIC OF)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IRN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'IRAQ');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IRQ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'IRELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'IRL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ISRAEL');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ISR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ITALY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ITA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'JAMAICA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'JAM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'JAPAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'JPN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'JORDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'JOR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KAZAKHSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KAZ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KENYA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KEN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KIRIBATI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KIR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KOREA, D.P.R.O.');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PRK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KOREA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KOR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KUWAIT');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KWT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'KYRGYZSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KGZ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LAOS ');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LAO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LATVIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LVA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LEBANON');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LBN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LESOTHO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LSO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LIBERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LBR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LIBYAN ARAB JAMAHIRIYA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LBY', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LIECHTENSTEIN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LIE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LITHUANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LTU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'LUXEMBURG');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LUX', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MACAU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MAC', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MACEDONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MKD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MADAGASCAR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MDG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MALAWI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MWI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MALAYSIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MYS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MALDIVES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MDV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MALI');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MLI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MALTA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MLT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MARSHALL ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MHL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MARTINIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MTQ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MAURITANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MRT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MAURITIUS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MUS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MAYOTTE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MYT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MEXICO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MEX', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MICRONESIA, FEDERATED STATES OF');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'FSM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MOLDOVA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MDA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MONACO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MCO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MONGOLIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MNG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MONTENEGRO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MNE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MONTSERRAT');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MSR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MOROCCO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MAR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MOZAMBIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MOZ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'MYANMAR (Burma) ');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MMR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NAMIBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NAM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NAURU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NRU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NEPAL');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NPL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NETHERLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NLD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NETHERLANDS ANTILLES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ANT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NEW CALEDONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NCL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NEW ZEALAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NZL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NICARAGUA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NIC', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NIGER');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NER', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NIGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NGA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NIUE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NIU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NORFOLK ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NFK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NORTHERN MARIANA ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'MNP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'NORWAY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'NOR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'OMAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'OMN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PAKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PAK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PALAU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PLW', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PANAMA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PAN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PAPUA NEW GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PNG', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PARAGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PRY', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PERU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PER', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PHILIPPINES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PHL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PITCAIRN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PCN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'POLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'POL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PORTUGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PRT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'PUERTO RICO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'PRI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'QATAR');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'QAT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'REUNION');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'REU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ROMANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ROM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'RUSSIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'RUS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'RWANDA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'RWA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAINT KITTS AND NEVIS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'KNA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAINT LUCIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LCA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VCT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'WSM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAN MARINO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SMR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAO TOME AND PRINCIPE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'STP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SAUDI ARABIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SAU', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SENEGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SEN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SERBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SRB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SEYCHELLES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SYC', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SIERRA LEONE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SLE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SINGAPORE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SGP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SLOVAKIA (Slovak Republic)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SVK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SLOVENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SVN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SOLOMON ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SLB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SOMALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SOM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SOUTH AFRICA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ZAF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SOUTH SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SSD', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SOUTH GEORGIA AND SOUTH S.S.');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SGS', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SPAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ESP', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SRI LANKA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'LKA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ST. HELENA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SHN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ST. PIERRE AND MIQUELON');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SPM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SDN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SURINAME');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SUR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SVALBARD AND JAN MAYEN ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SJM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SWAZILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SWZ', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SWEDEN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SWE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SWITZERLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'CHE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'SYRIAN ARAB REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'SYR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TAIWAN, PROVINCE OF CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TWN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TAJIKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TJK', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TZA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'THAILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'THA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TOGO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TGO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TOKELAU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TKL', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TONGA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TON', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TRINIDAD AND TOBAGO');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TTO', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TUNISIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TUN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TURKEY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TUR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TURKMENISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TKM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TURKS AND CAICOS ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TCA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'TUVALU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'TUV', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UGANDA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'UGA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UKRAINE');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'UKR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UNITED ARAB EMIRATES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ARE', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UNITED KINGDOM');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'GBR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UNITED STATES');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'USA', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'U.S. MINOR ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'UMI', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'URUGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'URY', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'UZBEKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'UZB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'VANUATU');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VUT', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'VENEZUELA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VEN', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'VIET NAM');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VNM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'VIRGIN ISLANDS (BRITISH)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VGB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'VIRGIN ISLANDS (U.S.)');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'VIR', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'WALLIS AND FUTUNA ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'WLF', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'WESTERN SAHARA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ESH', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'YEMEN');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'YEM', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ZAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ZMB', currval('text_seq'), id FROM entity_type WHERE code='country' ;
INSERT INTO text(id, default_value) VALUES (nextval('text_seq'), 'ZIMBABWE ');
INSERT INTO entity(id, code, text_id, entity_type_id) SELECT nextval('entity_seq'),'ZWE ', currval('text_seq'), id FROM entity_type WHERE code='country' ;

/*
ALTER SEQUENCE entity_type_seq RESTART WITH 3;
ALTER SEQUENCE entity_seq RESTART WITH 242;
ALTER SEQUENCE text_seq RESTART WITH 244;
*/