INSERT INTO text(id, default_value) VALUES (1001, 'AFGHANISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1001, 'AFG', 1001, 1);
INSERT INTO text(id, default_value) VALUES (1002, 'ALBANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1002, 'ALB', 1002, 1);
INSERT INTO text(id, default_value) VALUES (1003, 'ALGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1003, 'DZA', 1003, 1);
INSERT INTO text(id, default_value) VALUES (1004, 'AMERICAN SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1004, 'ASM', 1004, 1);
INSERT INTO text(id, default_value) VALUES (1005, 'ANDORRA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1005, 'AND', 1005, 1);
INSERT INTO text(id, default_value) VALUES (1006, 'ANGOLA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1006, 'AGO', 1006, 1);
INSERT INTO text(id, default_value) VALUES (1007, 'ANGUILLA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1007, 'AIA', 1007, 1);
INSERT INTO text(id, default_value) VALUES (1008, 'ANTARCTICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1008, 'ATA', 1008, 1);
INSERT INTO text(id, default_value) VALUES (1009, 'ANTIGUA AND BARBUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1009, 'ATG', 1009, 1);
INSERT INTO text(id, default_value) VALUES (1010, 'ARGENTINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1010, 'ARG', 1010, 1);
INSERT INTO text(id, default_value) VALUES (1011, 'ARMENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1011, 'ARM', 1011, 1);
INSERT INTO text(id, default_value) VALUES (1012, 'ARUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1012, 'ABW', 1012, 1);
INSERT INTO text(id, default_value) VALUES (1013, 'AUSTRALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1013, 'AUS', 1013, 1);
INSERT INTO text(id, default_value) VALUES (1014, 'AUSTRIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1014, 'AUT', 1014, 1);
INSERT INTO text(id, default_value) VALUES (1015, 'AZERBAIJAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1015, 'AZE', 1015, 1);
INSERT INTO text(id, default_value) VALUES (1016, 'BAHAMAS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1016, 'BHS', 1016, 1);
INSERT INTO text(id, default_value) VALUES (1017, 'BAHRAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1017, 'BHR', 1017, 1);
INSERT INTO text(id, default_value) VALUES (1018, 'BANGLADESH');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1018, 'BGD', 1018, 1);
INSERT INTO text(id, default_value) VALUES (1019, 'BARBADOS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1019, 'BRB', 1019, 1);
INSERT INTO text(id, default_value) VALUES (1020, 'BELARUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1020, 'BLR', 1020, 1);
INSERT INTO text(id, default_value) VALUES (1021, 'BELGIUM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1021, 'BEL', 1021, 1);
INSERT INTO text(id, default_value) VALUES (1022, 'BELIZE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1022, 'BLZ', 1022, 1);
INSERT INTO text(id, default_value) VALUES (1023, 'BENIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1023, 'BEN', 1023, 1);
INSERT INTO text(id, default_value) VALUES (1024, 'BERMUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1024, 'BMU', 1024, 1);
INSERT INTO text(id, default_value) VALUES (1025, 'BHUTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1025, 'BTN', 1025, 1);
INSERT INTO text(id, default_value) VALUES (1026, 'BOLIVIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1026, 'BOL', 1026, 1);
INSERT INTO text(id, default_value) VALUES (1027, 'BOSNIA AND HERZEGOWINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1027, 'BIH', 1027, 1);
INSERT INTO text(id, default_value) VALUES (1028, 'BOTSWANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1028, 'BWA', 1028, 1);
INSERT INTO text(id, default_value) VALUES (1029, 'BOUVET ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1029, 'BVT', 1029, 1);
INSERT INTO text(id, default_value) VALUES (1030, 'BRAZIL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1030, 'BRA', 1030, 1);
INSERT INTO text(id, default_value) VALUES (1031, 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1031, 'IOT', 1031, 1);
INSERT INTO text(id, default_value) VALUES (1032, 'BRUNEI DARUSSALAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1032, 'BRN', 1032, 1);
INSERT INTO text(id, default_value) VALUES (1033, 'BULGARIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1033, 'BGR', 1033, 1);
INSERT INTO text(id, default_value) VALUES (1034, 'BURKINA FASO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1034, 'BFA', 1034, 1);
INSERT INTO text(id, default_value) VALUES (1035, 'BURUNDI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1035, 'BDI', 1035, 1);
INSERT INTO text(id, default_value) VALUES (1036, 'CAMBODIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1036, 'KHM', 1036, 1);
INSERT INTO text(id, default_value) VALUES (1038, 'CANADA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1038, 'CAN', 1038, 1);
INSERT INTO text(id, default_value) VALUES (1039, 'CAPE VERDE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1039, 'CPV', 1039, 1);
INSERT INTO text(id, default_value) VALUES (1040, 'CAYMAN ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1040, 'CYM', 1040, 1);
INSERT INTO text(id, default_value) VALUES (1041, 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1041, 'CAF', 1041, 1);
INSERT INTO text(id, default_value) VALUES (1042, 'CHAD');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1042, 'TCD', 1042, 1);
INSERT INTO text(id, default_value) VALUES (1043, 'CHILE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1043, 'CHL', 1043, 1);
INSERT INTO text(id, default_value) VALUES (1044, 'CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1044, 'CHN', 1044, 1);
INSERT INTO text(id, default_value) VALUES (1045, 'CHRISTMAS ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1045, 'CXR', 1045, 1);
INSERT INTO text(id, default_value) VALUES (1046, 'COCOS (KEELING) ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1046, 'CCK', 1046, 1);
INSERT INTO text(id, default_value) VALUES (1047, 'COLOMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1047, 'COL', 1047, 1);
INSERT INTO text(id, default_value) VALUES (1048, 'COMOROS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1048, 'COM', 1048, 1);
INSERT INTO text(id, default_value) VALUES (1049, 'CONGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1049, 'COG', 1049, 1);
INSERT INTO text(id, default_value) VALUES (1050, 'CONGO, THE DRC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1050, 'COD', 1050, 1);
INSERT INTO text(id, default_value) VALUES (1051, 'COOK ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1051, 'COK', 1051, 1);
INSERT INTO text(id, default_value) VALUES (1052, 'COSTA RICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1052, 'CRI', 1052, 1);
INSERT INTO text(id, default_value) VALUES (1053, 'COTE D''IVOIRE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1053, 'CIV', 1053, 1);
INSERT INTO text(id, default_value) VALUES (1054, 'CROATIA (local name: Hrvatska)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1054, 'HRV', 1054, 1);
INSERT INTO text(id, default_value) VALUES (1055, 'CUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1055, 'CUB', 1055, 1);
INSERT INTO text(id, default_value) VALUES (1056, 'CYPRUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1056, 'CYP', 1056, 1);
INSERT INTO text(id, default_value) VALUES (1057, 'CZECH REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1057, 'CZE', 1057, 1);
INSERT INTO text(id, default_value) VALUES (1058, 'DENMARK');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1058, 'DNK', 1058, 1);
INSERT INTO text(id, default_value) VALUES (1059, 'DJIBOUTI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1059, 'DJI', 1059, 1);
INSERT INTO text(id, default_value) VALUES (1060, 'DOMINICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1060, 'DMA', 1060, 1);
INSERT INTO text(id, default_value) VALUES (1061, 'DOMINICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1061, 'DOM', 1061, 1);
INSERT INTO text(id, default_value) VALUES (1062, 'EAST TIMOR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1062, 'TMP', 1062, 1);
INSERT INTO text(id, default_value) VALUES (1063, 'ECUADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1063, 'ECU', 1063, 1);
INSERT INTO text(id, default_value) VALUES (1064, 'EGYPT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1064, 'EGY', 1064, 1);
INSERT INTO text(id, default_value) VALUES (1065, 'EL SALVADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1065, 'SLV', 1065, 1);
INSERT INTO text(id, default_value) VALUES (1066, 'EQUATORIAL GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1066, 'GNQ', 1066, 1);
INSERT INTO text(id, default_value) VALUES (1067, 'ERITREA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1067, 'ERI', 1067, 1);
INSERT INTO text(id, default_value) VALUES (1068, 'ESTONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1068, 'EST', 1068, 1);
INSERT INTO text(id, default_value) VALUES (1069, 'ETHIOPIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1069, 'ETH ', 1069, 1);
INSERT INTO text(id, default_value) VALUES (1070, 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1070, 'FLK', 1070, 1);
INSERT INTO text(id, default_value) VALUES (1071, 'FAROE ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1071, 'FRO', 1071, 1);
INSERT INTO text(id, default_value) VALUES (1072, 'FIJI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1072, 'FJI', 1072, 1);
INSERT INTO text(id, default_value) VALUES (1073, 'FINLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1073, 'FIN', 1073, 1);
INSERT INTO text(id, default_value) VALUES (1074, 'FRANCE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1074, 'FRA', 1074, 1);
INSERT INTO text(id, default_value) VALUES (1075, 'FRANCE, METROPOLITAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1075, 'FXX', 1075, 1);
INSERT INTO text(id, default_value) VALUES (1076, 'FRENCH GUIANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1076, 'GUF', 1076, 1);
INSERT INTO text(id, default_value) VALUES (1077, 'FRENCH POLYNESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1077, 'PYF', 1077, 1);
INSERT INTO text(id, default_value) VALUES (1078, 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1078, 'ATF', 1078, 1);
INSERT INTO text(id, default_value) VALUES (1079, 'GABON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1079, 'GAB', 1079, 1);
INSERT INTO text(id, default_value) VALUES (1080, 'GAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1080, 'GMB', 1080, 1);
INSERT INTO text(id, default_value) VALUES (1081, 'GEORGIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1081, 'GEO', 1081, 1);
INSERT INTO text(id, default_value) VALUES (1082, 'GERMANY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1082, 'DEU', 1082, 1);
INSERT INTO text(id, default_value) VALUES (1083, 'GHANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1083, 'GHA', 1083, 1);
INSERT INTO text(id, default_value) VALUES (1084, 'GIBRALTAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1084, 'GIB', 1084, 1);
INSERT INTO text(id, default_value) VALUES (1085, 'GREECE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1085, 'GRC', 1085, 1);
INSERT INTO text(id, default_value) VALUES (1086, 'GREENLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1086, 'GRL', 1086, 1);
INSERT INTO text(id, default_value) VALUES (1087, 'GRENADA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1087, 'GRD', 1087, 1);
INSERT INTO text(id, default_value) VALUES (1088, 'GUADELOUPE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1088, 'GLP', 1088, 1);
INSERT INTO text(id, default_value) VALUES (1089, 'GUAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1089, 'GUM', 1089, 1);
INSERT INTO text(id, default_value) VALUES (1090, 'GUATEMALA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1090, 'GTM', 1090, 1);
INSERT INTO text(id, default_value) VALUES (1091, 'GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1091, 'GIN', 1091, 1);
INSERT INTO text(id, default_value) VALUES (1092, 'GUINEA-BISSAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1092, 'GNB', 1092, 1);
INSERT INTO text(id, default_value) VALUES (1093, 'GUYANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1093, 'GUY', 1093, 1);
INSERT INTO text(id, default_value) VALUES (1094, 'HAITI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1094, 'HTI', 1094, 1);
INSERT INTO text(id, default_value) VALUES (1095, 'HEARD AND MC DONALD ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1095, 'HMD', 1095, 1);
INSERT INTO text(id, default_value) VALUES (1096, 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1096, 'VAT', 1096, 1);
INSERT INTO text(id, default_value) VALUES (1097, 'HONDURAS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1097, 'HND', 1097, 1);
INSERT INTO text(id, default_value) VALUES (1098, 'HONG KONG');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1098, 'HKG', 1098, 1);
INSERT INTO text(id, default_value) VALUES (1099, 'HUNGARY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1099, 'HUN', 1099, 1);
INSERT INTO text(id, default_value) VALUES (1100, 'ICELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1100, 'ISL', 1100, 1);
INSERT INTO text(id, default_value) VALUES (1101, 'INDIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1101, 'IND', 1101, 1);
INSERT INTO text(id, default_value) VALUES (1102, 'INDONESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1102, 'IDN', 1102, 1);
INSERT INTO text(id, default_value) VALUES (1103, 'IRAN (ISLAMIC REPUBLIC OF)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1103, 'IRN', 1103, 1);
INSERT INTO text(id, default_value) VALUES (1104, 'IRAQ');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1104, 'IRQ', 1104, 1);
INSERT INTO text(id, default_value) VALUES (1105, 'IRELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1105, 'IRL', 1105, 1);
INSERT INTO text(id, default_value) VALUES (1106, 'ISRAEL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1106, 'ISR', 1106, 1);
INSERT INTO text(id, default_value) VALUES (1107, 'ITALY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1107, 'ITA', 1107, 1);
INSERT INTO text(id, default_value) VALUES (1108, 'JAMAICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1108, 'JAM', 1108, 1);
INSERT INTO text(id, default_value) VALUES (1109, 'JAPAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1109, 'JPN', 1109, 1);
INSERT INTO text(id, default_value) VALUES (1110, 'JORDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1110, 'JOR', 1110, 1);
INSERT INTO text(id, default_value) VALUES (1111, 'KAZAKHSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1111, 'KAZ', 1111, 1);
INSERT INTO text(id, default_value) VALUES (1112, 'KENYA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1112, 'KEN', 1112, 1);
INSERT INTO text(id, default_value) VALUES (1113, 'KIRIBATI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1113, 'KIR', 1113, 1);
INSERT INTO text(id, default_value) VALUES (1114, 'KOREA, D.P.R.O.');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1114, 'PRK', 1114, 1);
INSERT INTO text(id, default_value) VALUES (1115, 'KOREA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1115, 'KOR', 1115, 1);
INSERT INTO text(id, default_value) VALUES (1116, 'KUWAIT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1116, 'KWT', 1116, 1);
INSERT INTO text(id, default_value) VALUES (1117, 'KYRGYZSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1117, 'KGZ', 1117, 1);
INSERT INTO text(id, default_value) VALUES (1118, 'LAOS ');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1118, 'LAO', 1118, 1);
INSERT INTO text(id, default_value) VALUES (1119, 'LATVIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1119, 'LVA', 1119, 1);
INSERT INTO text(id, default_value) VALUES (1120, 'LEBANON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1120, 'LBN', 1120, 1);
INSERT INTO text(id, default_value) VALUES (1121, 'LESOTHO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1121, 'LSO', 1121, 1);
INSERT INTO text(id, default_value) VALUES (1122, 'LIBERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1122, 'LBR', 1122, 1);
INSERT INTO text(id, default_value) VALUES (1123, 'LIBYAN ARAB JAMAHIRIYA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1123, 'LBY', 1123, 1);
INSERT INTO text(id, default_value) VALUES (1124, 'LIECHTENSTEIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1124, 'LIE', 1124, 1);
INSERT INTO text(id, default_value) VALUES (1125, 'LITHUANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1125, 'LTU', 1125, 1);
INSERT INTO text(id, default_value) VALUES (1127, 'MACAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1127, 'MAC', 1127, 1);
INSERT INTO text(id, default_value) VALUES (1128, 'MACEDONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1128, 'MKD', 1128, 1);
INSERT INTO text(id, default_value) VALUES (1129, 'MADAGASCAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1129, 'MDG', 1129, 1);
INSERT INTO text(id, default_value) VALUES (1130, 'MALAWI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1130, 'MWI', 1130, 1);
INSERT INTO text(id, default_value) VALUES (1131, 'MALAYSIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1131, 'MYS', 1131, 1);
INSERT INTO text(id, default_value) VALUES (1132, 'MALDIVES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1132, 'MDV', 1132, 1);
INSERT INTO text(id, default_value) VALUES (1133, 'MALI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1133, 'MLI', 1133, 1);
INSERT INTO text(id, default_value) VALUES (1134, 'MALTA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1134, 'MLT', 1134, 1);
INSERT INTO text(id, default_value) VALUES (1135, 'MARSHALL ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1135, 'MHL', 1135, 1);
INSERT INTO text(id, default_value) VALUES (1136, 'MARTINIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1136, 'MTQ', 1136, 1);
INSERT INTO text(id, default_value) VALUES (1137, 'MAURITANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1137, 'MRT', 1137, 1);
INSERT INTO text(id, default_value) VALUES (1138, 'MAURITIUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1138, 'MUS', 1138, 1);
INSERT INTO text(id, default_value) VALUES (1139, 'MAYOTTE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1139, 'MYT', 1139, 1);
INSERT INTO text(id, default_value) VALUES (1140, 'MEXICO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1140, 'MEX', 1140, 1);
INSERT INTO text(id, default_value) VALUES (1141, 'MICRONESIA, FEDERATED STATES OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1141, 'FSM', 1141, 1);
INSERT INTO text(id, default_value) VALUES (1142, 'MOLDOVA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1142, 'MDA', 1142, 1);
INSERT INTO text(id, default_value) VALUES (1143, 'MONACO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1143, 'MCO', 1143, 1);
INSERT INTO text(id, default_value) VALUES (1144, 'MONGOLIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1144, 'MNG', 1144, 1);
INSERT INTO text(id, default_value) VALUES (1145, 'MONTENEGRO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1145, 'MNE', 1145, 1);
INSERT INTO text(id, default_value) VALUES (1146, 'MONTSERRAT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1146, 'MSR', 1146, 1);
INSERT INTO text(id, default_value) VALUES (1147, 'MOROCCO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1147, 'MAR', 1147, 1);
INSERT INTO text(id, default_value) VALUES (1148, 'MOZAMBIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1148, 'MOZ', 1148, 1);
INSERT INTO text(id, default_value) VALUES (1149, 'MYANMAR (Burma) ');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1149, 'MMR', 1149, 1);
INSERT INTO text(id, default_value) VALUES (1150, 'NAMIBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1150, 'NAM', 1150, 1);
INSERT INTO text(id, default_value) VALUES (1151, 'NAURU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1151, 'NRU', 1151, 1);
INSERT INTO text(id, default_value) VALUES (1152, 'NEPAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1152, 'NPL', 1152, 1);
INSERT INTO text(id, default_value) VALUES (1153, 'NETHERLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1153, 'NLD', 1153, 1);
INSERT INTO text(id, default_value) VALUES (1154, 'NETHERLANDS ANTILLES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1154, 'ANT', 1154, 1);
INSERT INTO text(id, default_value) VALUES (1155, 'NEW CALEDONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1155, 'NCL', 1155, 1);
INSERT INTO text(id, default_value) VALUES (1156, 'NEW ZEALAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1156, 'NZL', 1156, 1);
INSERT INTO text(id, default_value) VALUES (1157, 'NICARAGUA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1157, 'NIC', 1157, 1);
INSERT INTO text(id, default_value) VALUES (1158, 'NIGER');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1158, 'NER', 1158, 1);
INSERT INTO text(id, default_value) VALUES (1159, 'NIGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1159, 'NGA', 1159, 1);
INSERT INTO text(id, default_value) VALUES (1160, 'NIUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1160, 'NIU', 1160, 1);
INSERT INTO text(id, default_value) VALUES (1161, 'NORFOLK ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1161, 'NFK', 1161, 1);
INSERT INTO text(id, default_value) VALUES (1162, 'NORTHERN MARIANA ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1162, 'MNP', 1162, 1);
INSERT INTO text(id, default_value) VALUES (1163, 'NORWAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1163, 'NOR', 1163, 1);
INSERT INTO text(id, default_value) VALUES (1164, 'OMAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1164, 'OMN', 1164, 1);
INSERT INTO text(id, default_value) VALUES (1165, 'PAKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1165, 'PAK', 1165, 1);
INSERT INTO text(id, default_value) VALUES (1166, 'PALAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1166, 'PLW', 1166, 1);
INSERT INTO text(id, default_value) VALUES (1167, 'PANAMA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1167, 'PAN', 1167, 1);
INSERT INTO text(id, default_value) VALUES (1168, 'PAPUA NEW GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1168, 'PNG', 1168, 1);
INSERT INTO text(id, default_value) VALUES (1169, 'PARAGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1169, 'PRY', 1169, 1);
INSERT INTO text(id, default_value) VALUES (1170, 'PERU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1170, 'PER', 1170, 1);
INSERT INTO text(id, default_value) VALUES (1171, 'PHILIPPINES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1171, 'PHL', 1171, 1);
INSERT INTO text(id, default_value) VALUES (1172, 'PITCAIRN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1172, 'PCN', 1172, 1);
INSERT INTO text(id, default_value) VALUES (1173, 'POLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1173, 'POL', 1173, 1);
INSERT INTO text(id, default_value) VALUES (1174, 'PORTUGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1174, 'PRT', 1174, 1);
INSERT INTO text(id, default_value) VALUES (1175, 'PUERTO RICO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1175, 'PRI', 1175, 1);
INSERT INTO text(id, default_value) VALUES (1176, 'QATAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1176, 'QAT', 1176, 1);
INSERT INTO text(id, default_value) VALUES (1177, 'REUNION');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1177, 'REU', 1177, 1);
INSERT INTO text(id, default_value) VALUES (1178, 'ROMANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1178, 'ROM', 1178, 1);
INSERT INTO text(id, default_value) VALUES (1181, 'SAINT KITTS AND NEVIS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1181, 'KNA', 1181, 1);
INSERT INTO text(id, default_value) VALUES (1182, 'SAINT LUCIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1182, 'LCA', 1182, 1);
INSERT INTO text(id, default_value) VALUES (1183, 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1183, 'VCT', 1183, 1);
INSERT INTO text(id, default_value) VALUES (1184, 'SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1184, 'WSM', 1184, 1);
INSERT INTO text(id, default_value) VALUES (1185, 'SAN MARINO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1185, 'SMR', 1185, 1);
INSERT INTO text(id, default_value) VALUES (1186, 'SAO TOME AND PRINCIPE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1186, 'STP', 1186, 1);
INSERT INTO text(id, default_value) VALUES (1187, 'SAUDI ARABIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1187, 'SAU', 1187, 1);
INSERT INTO text(id, default_value) VALUES (1188, 'SENEGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1188, 'SEN', 1188, 1);
INSERT INTO text(id, default_value) VALUES (1189, 'SERBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1189, 'SRB', 1189, 1);
INSERT INTO text(id, default_value) VALUES (1190, 'SEYCHELLES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1190, 'SYC', 1190, 1);
INSERT INTO text(id, default_value) VALUES (1191, 'SIERRA LEONE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1191, 'SLE', 1191, 1);
INSERT INTO text(id, default_value) VALUES (1192, 'SINGAPORE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1192, 'SGP', 1192, 1);
INSERT INTO text(id, default_value) VALUES (1193, 'SLOVAKIA (Slovak Republic)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1193, 'SVK', 1193, 1);
INSERT INTO text(id, default_value) VALUES (1194, 'SLOVENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1194, 'SVN', 1194, 1);
INSERT INTO text(id, default_value) VALUES (1195, 'SOLOMON ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1195, 'SLB', 1195, 1);
INSERT INTO text(id, default_value) VALUES (1196, 'SOMALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1196, 'SOM', 1196, 1);
INSERT INTO text(id, default_value) VALUES (1197, 'SOUTH AFRICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1197, 'ZAF', 1197, 1);
INSERT INTO text(id, default_value) VALUES (1198, 'SOUTH SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1198, 'SSD', 1198, 1);
INSERT INTO text(id, default_value) VALUES (1199, 'SOUTH GEORGIA AND SOUTH S.S.');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1199, 'SGS', 1199, 1);
INSERT INTO text(id, default_value) VALUES (1200, 'SPAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1200, 'ESP', 1200, 1);
INSERT INTO text(id, default_value) VALUES (1201, 'SRI LANKA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1201, 'LKA', 1201, 1);
INSERT INTO text(id, default_value) VALUES (1202, 'ST. HELENA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1202, 'SHN', 1202, 1);
INSERT INTO text(id, default_value) VALUES (1203, 'ST. PIERRE AND MIQUELON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1203, 'SPM', 1203, 1);
INSERT INTO text(id, default_value) VALUES (1204, 'SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1204, 'SDN', 1204, 1);
INSERT INTO text(id, default_value) VALUES (1205, 'SURINAME');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1205, 'SUR', 1205, 1);
INSERT INTO text(id, default_value) VALUES (1206, 'SVALBARD AND JAN MAYEN ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1206, 'SJM', 1206, 1);
INSERT INTO text(id, default_value) VALUES (1207, 'SWAZILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1207, 'SWZ', 1207, 1);
INSERT INTO text(id, default_value) VALUES (1208, 'SWEDEN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1208, 'SWE', 1208, 1);
INSERT INTO text(id, default_value) VALUES (1209, 'SWITZERLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1209, 'CHE', 1209, 1);
INSERT INTO text(id, default_value) VALUES (1210, 'SYRIAN ARAB REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1210, 'SYR', 1210, 1);
INSERT INTO text(id, default_value) VALUES (1211, 'TAIWAN, PROVINCE OF CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1211, 'TWN', 1211, 1);
INSERT INTO text(id, default_value) VALUES (1212, 'TAJIKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1212, 'TJK', 1212, 1);
INSERT INTO text(id, default_value) VALUES (1213, 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1213, 'TZA', 1213, 1);
INSERT INTO text(id, default_value) VALUES (1214, 'THAILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1214, 'THA', 1214, 1);
INSERT INTO text(id, default_value) VALUES (1215, 'TOGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1215, 'TGO', 1215, 1);
INSERT INTO text(id, default_value) VALUES (1216, 'TOKELAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1216, 'TKL', 1216, 1);
INSERT INTO text(id, default_value) VALUES (1217, 'TONGA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1217, 'TON', 1217, 1);
INSERT INTO text(id, default_value) VALUES (1218, 'TRINIDAD AND TOBAGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1218, 'TTO', 1218, 1);
INSERT INTO text(id, default_value) VALUES (1219, 'TUNISIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1219, 'TUN', 1219, 1);
INSERT INTO text(id, default_value) VALUES (1220, 'TURKEY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1220, 'TUR', 1220, 1);
INSERT INTO text(id, default_value) VALUES (1221, 'TURKMENISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1221, 'TKM', 1221, 1);
INSERT INTO text(id, default_value) VALUES (1222, 'TURKS AND CAICOS ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1222, 'TCA', 1222, 1);
INSERT INTO text(id, default_value) VALUES (1223, 'TUVALU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1223, 'TUV', 1223, 1);
INSERT INTO text(id, default_value) VALUES (1224, 'UGANDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1224, 'UGA', 1224, 1);
INSERT INTO text(id, default_value) VALUES (1225, 'UKRAINE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1225, 'UKR', 1225, 1);
INSERT INTO text(id, default_value) VALUES (1226, 'UNITED ARAB EMIRATES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1226, 'ARE', 1226, 1);
INSERT INTO text(id, default_value) VALUES (1227, 'UNITED KINGDOM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1227, 'GBR', 1227, 1);
INSERT INTO text(id, default_value) VALUES (1228, 'UNITED STATES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1228, 'USA', 1228, 1);
INSERT INTO text(id, default_value) VALUES (1229, 'U.S. MINOR ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1229, 'UMI', 1229, 1);
INSERT INTO text(id, default_value) VALUES (1230, 'URUGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1230, 'URY', 1230, 1);
INSERT INTO text(id, default_value) VALUES (1231, 'UZBEKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1231, 'UZB', 1231, 1);
INSERT INTO text(id, default_value) VALUES (1232, 'VANUATU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1232, 'VUT', 1232, 1);
INSERT INTO text(id, default_value) VALUES (1233, 'VENEZUELA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1233, 'VEN', 1233, 1);
INSERT INTO text(id, default_value) VALUES (1234, 'VIET NAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1234, 'VNM', 1234, 1);
INSERT INTO text(id, default_value) VALUES (1235, 'VIRGIN ISLANDS (BRITISH)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1235, 'VGB', 1235, 1);
INSERT INTO text(id, default_value) VALUES (1236, 'VIRGIN ISLANDS (U.S.)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1236, 'VIR', 1236, 1);
INSERT INTO text(id, default_value) VALUES (1237, 'WALLIS AND FUTUNA ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1237, 'WLF', 1237, 1);
INSERT INTO text(id, default_value) VALUES (1238, 'WESTERN SAHARA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1238, 'ESH', 1238, 1);
INSERT INTO text(id, default_value) VALUES (1239, 'YEMEN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1239, 'YEM', 1239, 1);
INSERT INTO text(id, default_value) VALUES (1240, 'ZAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1240, 'ZMB', 1240, 1);
INSERT INTO text(id, default_value) VALUES (1241, 'ZIMBABWE ');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1241, 'ZWE ', 1241, 1);

ALTER SEQUENCE entity_seq RESTART WITH 2000;
ALTER SEQUENCE text_seq RESTART WITH 2000;
