INSERT INTO text(id, default_value) VALUES (1001, 'AFGHANISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1001, 'AF', 1001, 1);
INSERT INTO text(id, default_value) VALUES (1002, 'ÅLAND ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1002, 'AX', 1002, 1);
INSERT INTO text(id, default_value) VALUES (1003, 'ALBANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1003, 'AL', 1003, 1);
INSERT INTO text(id, default_value) VALUES (1004, 'ALGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1004, 'DZ', 1004, 1);
INSERT INTO text(id, default_value) VALUES (1005, 'AMERICAN SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1005, 'AS', 1005, 1);
INSERT INTO text(id, default_value) VALUES (1006, 'ANDORRA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1006, 'AD', 1006, 1);
INSERT INTO text(id, default_value) VALUES (1007, 'ANGOLA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1007, 'AO', 1007, 1);
INSERT INTO text(id, default_value) VALUES (1008, 'ANGUILLA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1008, 'AI', 1008, 1);
INSERT INTO text(id, default_value) VALUES (1009, 'ANTARCTICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1009, 'AQ', 1009, 1);
INSERT INTO text(id, default_value) VALUES (1010, 'ANTIGUA AND BARBUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1010, 'AG', 1010, 1);
INSERT INTO text(id, default_value) VALUES (1011, 'ARGENTINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1011, 'AR', 1011, 1);
INSERT INTO text(id, default_value) VALUES (1012, 'ARMENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1012, 'AM', 1012, 1);
INSERT INTO text(id, default_value) VALUES (1013, 'ARUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1013, 'AW', 1013, 1);
INSERT INTO text(id, default_value) VALUES (1014, 'AUSTRALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1014, 'AU', 1014, 1);
INSERT INTO text(id, default_value) VALUES (1015, 'AUSTRIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1015, 'AT', 1015, 1);
INSERT INTO text(id, default_value) VALUES (1016, 'AZERBAIJAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1016, 'AZ', 1016, 1);
INSERT INTO text(id, default_value) VALUES (1017, 'BAHAMAS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1017, 'BS', 1017, 1);
INSERT INTO text(id, default_value) VALUES (1018, 'BAHRAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1018, 'BH', 1018, 1);
INSERT INTO text(id, default_value) VALUES (1019, 'BANGLADESH');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1019, 'BD', 1019, 1);
INSERT INTO text(id, default_value) VALUES (1020, 'BARBADOS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1020, 'BB', 1020, 1);
INSERT INTO text(id, default_value) VALUES (1021, 'BELARUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1021, 'BY', 1021, 1);
INSERT INTO text(id, default_value) VALUES (1022, 'BELGIUM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1022, 'BE', 1022, 1);
INSERT INTO text(id, default_value) VALUES (1023, 'BELIZE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1023, 'BZ', 1023, 1);
INSERT INTO text(id, default_value) VALUES (1024, 'BENIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1024, 'BJ', 1024, 1);
INSERT INTO text(id, default_value) VALUES (1025, 'BERMUDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1025, 'BM', 1025, 1);
INSERT INTO text(id, default_value) VALUES (1026, 'BHUTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1026, 'BT', 1026, 1);
INSERT INTO text(id, default_value) VALUES (1027, 'BOLIVIA, PLURINATIONAL STATE OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1027, 'BO', 1027, 1);
INSERT INTO text(id, default_value) VALUES (1028, 'BONAIRE, SINT EUSTATIUS AND SABA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1028, 'BQ', 1028, 1);
INSERT INTO text(id, default_value) VALUES (1029, 'BOSNIA AND HERZEGOVINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1029, 'BA', 1029, 1);
INSERT INTO text(id, default_value) VALUES (1030, 'BOTSWANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1030, 'BW', 1030, 1);
INSERT INTO text(id, default_value) VALUES (1031, 'BOUVET ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1031, 'BV', 1031, 1);
INSERT INTO text(id, default_value) VALUES (1032, 'BRAZIL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1032, 'BR', 1032, 1);
INSERT INTO text(id, default_value) VALUES (1033, 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1033, 'IO', 1033, 1);
INSERT INTO text(id, default_value) VALUES (1034, 'BRUNEI DARUSSALAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1034, 'BN', 1034, 1);
INSERT INTO text(id, default_value) VALUES (1035, 'BULGARIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1035, 'BG', 1035, 1);
INSERT INTO text(id, default_value) VALUES (1036, 'BURKINA FASO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1036, 'BF', 1036, 1);
INSERT INTO text(id, default_value) VALUES (1037, 'BURUNDI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1037, 'BI', 1037, 1);
INSERT INTO text(id, default_value) VALUES (1038, 'CAMBODIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1038, 'KH', 1038, 1);
INSERT INTO text(id, default_value) VALUES (1039, 'CAMEROON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1039, 'CM', 1039, 1);
INSERT INTO text(id, default_value) VALUES (1040, 'CANADA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1040, 'CA', 1040, 1);
INSERT INTO text(id, default_value) VALUES (1041, 'CAPE VERDE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1041, 'CV', 1041, 1);
INSERT INTO text(id, default_value) VALUES (1042, 'CAYMAN ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1042, 'KY', 1042, 1);
INSERT INTO text(id, default_value) VALUES (1043, 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1043, 'CF', 1043, 1);
INSERT INTO text(id, default_value) VALUES (1044, 'CHAD');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1044, 'TD', 1044, 1);
INSERT INTO text(id, default_value) VALUES (1045, 'CHILE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1045, 'CL', 1045, 1);
INSERT INTO text(id, default_value) VALUES (1046, 'CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1046, 'CN', 1046, 1);
INSERT INTO text(id, default_value) VALUES (1047, 'CHRISTMAS ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1047, 'CX', 1047, 1);
INSERT INTO text(id, default_value) VALUES (1048, 'COCOS (KEELING) ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1048, 'CC', 1048, 1);
INSERT INTO text(id, default_value) VALUES (1049, 'COLOMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1049, 'CO', 1049, 1);
INSERT INTO text(id, default_value) VALUES (1050, 'COMOROS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1050, 'KM', 1050, 1);
INSERT INTO text(id, default_value) VALUES (1051, 'CONGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1051, 'CG', 1051, 1);
INSERT INTO text(id, default_value) VALUES (1052, 'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1052, 'CD', 1052, 1);
INSERT INTO text(id, default_value) VALUES (1053, 'COOK ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1053, 'CK', 1053, 1);
INSERT INTO text(id, default_value) VALUES (1054, 'COSTA RICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1054, 'CR', 1054, 1);
INSERT INTO text(id, default_value) VALUES (1055, 'CÔTE D''IVOIRE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1055, 'CI', 1055, 1);
INSERT INTO text(id, default_value) VALUES (1056, 'CROATIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1056, 'HR', 1056, 1);
INSERT INTO text(id, default_value) VALUES (1057, 'CUBA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1057, 'CU', 1057, 1);
INSERT INTO text(id, default_value) VALUES (1058, 'CURAÇAO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1058, 'CW', 1058, 1);
INSERT INTO text(id, default_value) VALUES (1059, 'CYPRUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1059, 'CY', 1059, 1);
INSERT INTO text(id, default_value) VALUES (1060, 'CZECH REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1060, 'CZ', 1060, 1);
INSERT INTO text(id, default_value) VALUES (1061, 'DENMARK');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1061, 'DK', 1061, 1);
INSERT INTO text(id, default_value) VALUES (1062, 'DJIBOUTI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1062, 'DJ', 1062, 1);
INSERT INTO text(id, default_value) VALUES (1063, 'DOMINICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1063, 'DM', 1063, 1);
INSERT INTO text(id, default_value) VALUES (1064, 'DOMINICAN REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1064, 'DO', 1064, 1);
INSERT INTO text(id, default_value) VALUES (1065, 'ECUADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1065, 'EC', 1065, 1);
INSERT INTO text(id, default_value) VALUES (1066, 'EGYPT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1066, 'EG', 1066, 1);
INSERT INTO text(id, default_value) VALUES (1067, 'EL SALVADOR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1067, 'SV', 1067, 1);
INSERT INTO text(id, default_value) VALUES (1068, 'EQUATORIAL GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1068, 'GQ', 1068, 1);
INSERT INTO text(id, default_value) VALUES (1069, 'ERITREA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1069, 'ER', 1069, 1);
INSERT INTO text(id, default_value) VALUES (1070, 'ESTONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1070, 'EE', 1070, 1);
INSERT INTO text(id, default_value) VALUES (1071, 'ETHIOPIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1071, 'ET', 1071, 1);
INSERT INTO text(id, default_value) VALUES (1072, 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1072, 'FK', 1072, 1);
INSERT INTO text(id, default_value) VALUES (1073, 'FAROE ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1073, 'FO', 1073, 1);
INSERT INTO text(id, default_value) VALUES (1074, 'FIJI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1074, 'FJ', 1074, 1);
INSERT INTO text(id, default_value) VALUES (1075, 'FINLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1075, 'FI', 1075, 1);
INSERT INTO text(id, default_value) VALUES (1076, 'FRANCE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1076, 'FR', 1076, 1);
INSERT INTO text(id, default_value) VALUES (1077, 'FRENCH GUIANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1077, 'GF', 1077, 1);
INSERT INTO text(id, default_value) VALUES (1078, 'FRENCH POLYNESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1078, 'PF', 1078, 1);
INSERT INTO text(id, default_value) VALUES (1079, 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1079, 'TF', 1079, 1);
INSERT INTO text(id, default_value) VALUES (1080, 'GABON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1080, 'GA', 1080, 1);
INSERT INTO text(id, default_value) VALUES (1081, 'GAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1081, 'GM', 1081, 1);
INSERT INTO text(id, default_value) VALUES (1082, 'GEORGIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1082, 'GE', 1082, 1);
INSERT INTO text(id, default_value) VALUES (1083, 'GERMANY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1083, 'DE', 1083, 1);
INSERT INTO text(id, default_value) VALUES (1084, 'GHANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1084, 'GH', 1084, 1);
INSERT INTO text(id, default_value) VALUES (1085, 'GIBRALTAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1085, 'GI', 1085, 1);
INSERT INTO text(id, default_value) VALUES (1086, 'GREECE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1086, 'GR', 1086, 1);
INSERT INTO text(id, default_value) VALUES (1087, 'GREENLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1087, 'GL', 1087, 1);
INSERT INTO text(id, default_value) VALUES (1088, 'GRENADA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1088, 'GD', 1088, 1);
INSERT INTO text(id, default_value) VALUES (1089, 'GUADELOUPE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1089, 'GP', 1089, 1);
INSERT INTO text(id, default_value) VALUES (1090, 'GUAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1090, 'GU', 1090, 1);
INSERT INTO text(id, default_value) VALUES (1091, 'GUATEMALA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1091, 'GT', 1091, 1);
INSERT INTO text(id, default_value) VALUES (1092, 'GUERNSEY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1092, 'GG', 1092, 1);
INSERT INTO text(id, default_value) VALUES (1093, 'GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1093, 'GN', 1093, 1);
INSERT INTO text(id, default_value) VALUES (1094, 'GUINEA-BISSAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1094, 'GW', 1094, 1);
INSERT INTO text(id, default_value) VALUES (1095, 'GUYANA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1095, 'GY', 1095, 1);
INSERT INTO text(id, default_value) VALUES (1096, 'HAITI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1096, 'HT', 1096, 1);
INSERT INTO text(id, default_value) VALUES (1097, 'HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1097, 'HM', 1097, 1);
INSERT INTO text(id, default_value) VALUES (1098, 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1098, 'VA', 1098, 1);
INSERT INTO text(id, default_value) VALUES (1099, 'HONDURAS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1099, 'HN', 1099, 1);
INSERT INTO text(id, default_value) VALUES (1100, 'HONG KONG');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1100, 'HK', 1100, 1);
INSERT INTO text(id, default_value) VALUES (1101, 'HUNGARY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1101, 'HU', 1101, 1);
INSERT INTO text(id, default_value) VALUES (1102, 'ICELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1102, 'IS', 1102, 1);
INSERT INTO text(id, default_value) VALUES (1103, 'INDIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1103, 'IN', 1103, 1);
INSERT INTO text(id, default_value) VALUES (1104, 'INDONESIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1104, 'ID', 1104, 1);
INSERT INTO text(id, default_value) VALUES (1105, 'IRAN, ISLAMIC REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1105, 'IR', 1105, 1);
INSERT INTO text(id, default_value) VALUES (1106, 'IRAQ');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1106, 'IQ', 1106, 1);
INSERT INTO text(id, default_value) VALUES (1107, 'IRELAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1107, 'IE', 1107, 1);
INSERT INTO text(id, default_value) VALUES (1108, 'ISLE OF MAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1108, 'IM', 1108, 1);
INSERT INTO text(id, default_value) VALUES (1109, 'ISRAEL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1109, 'IL', 1109, 1);
INSERT INTO text(id, default_value) VALUES (1110, 'ITALY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1110, 'IT', 1110, 1);
INSERT INTO text(id, default_value) VALUES (1111, 'JAMAICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1111, 'JM', 1111, 1);
INSERT INTO text(id, default_value) VALUES (1112, 'JAPAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1112, 'JP', 1112, 1);
INSERT INTO text(id, default_value) VALUES (1113, 'JERSEY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1113, 'JE', 1113, 1);
INSERT INTO text(id, default_value) VALUES (1114, 'JORDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1114, 'JO', 1114, 1);
INSERT INTO text(id, default_value) VALUES (1115, 'KAZAKHSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1115, 'KZ', 1115, 1);
INSERT INTO text(id, default_value) VALUES (1116, 'KENYA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1116, 'KE', 1116, 1);
INSERT INTO text(id, default_value) VALUES (1117, 'KIRIBATI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1117, 'KI', 1117, 1);
INSERT INTO text(id, default_value) VALUES (1118, 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1118, 'KP', 1118, 1);
INSERT INTO text(id, default_value) VALUES (1119, 'KOREA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1119, 'KR', 1119, 1);
INSERT INTO text(id, default_value) VALUES (1120, 'KUWAIT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1120, 'KW', 1120, 1);
INSERT INTO text(id, default_value) VALUES (1121, 'KYRGYZSTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1121, 'KG', 1121, 1);
INSERT INTO text(id, default_value) VALUES (1122, 'LAO PEOPLE''S DEMOCRATIC REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1122, 'LA', 1122, 1);
INSERT INTO text(id, default_value) VALUES (1123, 'LATVIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1123, 'LV', 1123, 1);
INSERT INTO text(id, default_value) VALUES (1124, 'LEBANON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1124, 'LB', 1124, 1);
INSERT INTO text(id, default_value) VALUES (1125, 'LESOTHO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1125, 'LS', 1125, 1);
INSERT INTO text(id, default_value) VALUES (1126, 'LIBERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1126, 'LR', 1126, 1);
INSERT INTO text(id, default_value) VALUES (1127, 'LIBYA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1127, 'LY', 1127, 1);
INSERT INTO text(id, default_value) VALUES (1128, 'LIECHTENSTEIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1128, 'LI', 1128, 1);
INSERT INTO text(id, default_value) VALUES (1129, 'LITHUANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1129, 'LT', 1129, 1);
INSERT INTO text(id, default_value) VALUES (1130, 'LUXEMBOURG');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1130, 'LU', 1130, 1);
INSERT INTO text(id, default_value) VALUES (1131, 'MACAO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1131, 'MO', 1131, 1);
INSERT INTO text(id, default_value) VALUES (1132, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1132, 'MK', 1132, 1);
INSERT INTO text(id, default_value) VALUES (1133, 'MADAGASCAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1133, 'MG', 1133, 1);
INSERT INTO text(id, default_value) VALUES (1134, 'MALAWI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1134, 'MW', 1134, 1);
INSERT INTO text(id, default_value) VALUES (1135, 'MALAYSIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1135, 'MY', 1135, 1);
INSERT INTO text(id, default_value) VALUES (1136, 'MALDIVES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1136, 'MV', 1136, 1);
INSERT INTO text(id, default_value) VALUES (1137, 'MALI');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1137, 'ML', 1137, 1);
INSERT INTO text(id, default_value) VALUES (1138, 'MALTA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1138, 'MT', 1138, 1);
INSERT INTO text(id, default_value) VALUES (1139, 'MARSHALL ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1139, 'MH', 1139, 1);
INSERT INTO text(id, default_value) VALUES (1140, 'MARTINIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1140, 'MQ', 1140, 1);
INSERT INTO text(id, default_value) VALUES (1141, 'MAURITANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1141, 'MR', 1141, 1);
INSERT INTO text(id, default_value) VALUES (1142, 'MAURITIUS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1142, 'MU', 1142, 1);
INSERT INTO text(id, default_value) VALUES (1143, 'MAYOTTE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1143, 'YT', 1143, 1);
INSERT INTO text(id, default_value) VALUES (1144, 'MEXICO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1144, 'MX', 1144, 1);
INSERT INTO text(id, default_value) VALUES (1145, 'MICRONESIA, FEDERATED STATES OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1145, 'FM', 1145, 1);
INSERT INTO text(id, default_value) VALUES (1146, 'MOLDOVA, REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1146, 'MD', 1146, 1);
INSERT INTO text(id, default_value) VALUES (1147, 'MONACO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1147, 'MC', 1147, 1);
INSERT INTO text(id, default_value) VALUES (1148, 'MONGOLIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1148, 'MN', 1148, 1);
INSERT INTO text(id, default_value) VALUES (1149, 'MONTENEGRO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1149, 'ME', 1149, 1);
INSERT INTO text(id, default_value) VALUES (1150, 'MONTSERRAT');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1150, 'MS', 1150, 1);
INSERT INTO text(id, default_value) VALUES (1151, 'MOROCCO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1151, 'MA', 1151, 1);
INSERT INTO text(id, default_value) VALUES (1152, 'MOZAMBIQUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1152, 'MZ', 1152, 1);
INSERT INTO text(id, default_value) VALUES (1153, 'MYANMAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1153, 'MM', 1153, 1);
INSERT INTO text(id, default_value) VALUES (1154, 'NAMIBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1154, 'NA', 1154, 1);
INSERT INTO text(id, default_value) VALUES (1155, 'NAURU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1155, 'NR', 1155, 1);
INSERT INTO text(id, default_value) VALUES (1156, 'NEPAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1156, 'NP', 1156, 1);
INSERT INTO text(id, default_value) VALUES (1157, 'NETHERLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1157, 'NL', 1157, 1);
INSERT INTO text(id, default_value) VALUES (1158, 'NEW CALEDONIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1158, 'NC', 1158, 1);
INSERT INTO text(id, default_value) VALUES (1159, 'NEW ZEALAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1159, 'NZ', 1159, 1);
INSERT INTO text(id, default_value) VALUES (1160, 'NICARAGUA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1160, 'NI', 1160, 1);
INSERT INTO text(id, default_value) VALUES (1161, 'NIGER');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1161, 'NE', 1161, 1);
INSERT INTO text(id, default_value) VALUES (1162, 'NIGERIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1162, 'NG', 1162, 1);
INSERT INTO text(id, default_value) VALUES (1163, 'NIUE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1163, 'NU', 1163, 1);
INSERT INTO text(id, default_value) VALUES (1164, 'NORFOLK ISLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1164, 'NF', 1164, 1);
INSERT INTO text(id, default_value) VALUES (1165, 'NORTHERN MARIANA ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1165, 'MP', 1165, 1);
INSERT INTO text(id, default_value) VALUES (1166, 'NORWAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1166, 'NO', 1166, 1);
INSERT INTO text(id, default_value) VALUES (1167, 'OMAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1167, 'OM', 1167, 1);
INSERT INTO text(id, default_value) VALUES (1168, 'PAKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1168, 'PK', 1168, 1);
INSERT INTO text(id, default_value) VALUES (1169, 'PALAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1169, 'PW', 1169, 1);
INSERT INTO text(id, default_value) VALUES (1170, 'PALESTINE, STATE OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1170, 'PS', 1170, 1);
INSERT INTO text(id, default_value) VALUES (1171, 'PANAMA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1171, 'PA', 1171, 1);
INSERT INTO text(id, default_value) VALUES (1172, 'PAPUA NEW GUINEA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1172, 'PG', 1172, 1);
INSERT INTO text(id, default_value) VALUES (1173, 'PARAGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1173, 'PY', 1173, 1);
INSERT INTO text(id, default_value) VALUES (1174, 'PERU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1174, 'PE', 1174, 1);
INSERT INTO text(id, default_value) VALUES (1175, 'PHILIPPINES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1175, 'PH', 1175, 1);
INSERT INTO text(id, default_value) VALUES (1176, 'PITCAIRN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1176, 'PN', 1176, 1);
INSERT INTO text(id, default_value) VALUES (1177, 'POLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1177, 'PL', 1177, 1);
INSERT INTO text(id, default_value) VALUES (1178, 'PORTUGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1178, 'PT', 1178, 1);
INSERT INTO text(id, default_value) VALUES (1179, 'PUERTO RICO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1179, 'PR', 1179, 1);
INSERT INTO text(id, default_value) VALUES (1180, 'QATAR');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1180, 'QA', 1180, 1);
INSERT INTO text(id, default_value) VALUES (1181, 'RÉUNION');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1181, 'RE', 1181, 1);
INSERT INTO text(id, default_value) VALUES (1182, 'ROMANIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1182, 'RO', 1182, 1);
INSERT INTO text(id, default_value) VALUES (1183, 'RUSSIAN FEDERATION');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1183, 'RU', 1183, 1);
INSERT INTO text(id, default_value) VALUES (1184, 'RWANDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1184, 'RW', 1184, 1);
INSERT INTO text(id, default_value) VALUES (1185, 'SAINT BARTHÉLEMY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1185, 'BL', 1185, 1);
INSERT INTO text(id, default_value) VALUES (1186, 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1186, 'SH', 1186, 1);
INSERT INTO text(id, default_value) VALUES (1187, 'SAINT KITTS AND NEVIS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1187, 'KN', 1187, 1);
INSERT INTO text(id, default_value) VALUES (1188, 'SAINT LUCIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1188, 'LC', 1188, 1);
INSERT INTO text(id, default_value) VALUES (1189, 'SAINT MARTIN (FRENCH PART)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1189, 'MF', 1189, 1);
INSERT INTO text(id, default_value) VALUES (1190, 'SAINT PIERRE AND MIQUELON');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1190, 'PM', 1190, 1);
INSERT INTO text(id, default_value) VALUES (1191, 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1191, 'VC', 1191, 1);
INSERT INTO text(id, default_value) VALUES (1192, 'SAMOA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1192, 'WS', 1192, 1);
INSERT INTO text(id, default_value) VALUES (1193, 'SAN MARINO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1193, 'SM', 1193, 1);
INSERT INTO text(id, default_value) VALUES (1194, 'SAO TOME AND PRINCIPE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1194, 'ST', 1194, 1);
INSERT INTO text(id, default_value) VALUES (1195, 'SAUDI ARABIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1195, 'SA', 1195, 1);
INSERT INTO text(id, default_value) VALUES (1196, 'SENEGAL');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1196, 'SN', 1196, 1);
INSERT INTO text(id, default_value) VALUES (1197, 'SERBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1197, 'RS', 1197, 1);
INSERT INTO text(id, default_value) VALUES (1198, 'SEYCHELLES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1198, 'SC', 1198, 1);
INSERT INTO text(id, default_value) VALUES (1199, 'SIERRA LEONE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1199, 'SL', 1199, 1);
INSERT INTO text(id, default_value) VALUES (1200, 'SINGAPORE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1200, 'SG', 1200, 1);
INSERT INTO text(id, default_value) VALUES (1201, 'SINT MAARTEN (DUTCH PART)');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1201, 'SX', 1201, 1);
INSERT INTO text(id, default_value) VALUES (1202, 'SLOVAKIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1202, 'SK', 1202, 1);
INSERT INTO text(id, default_value) VALUES (1203, 'SLOVENIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1203, 'SI', 1203, 1);
INSERT INTO text(id, default_value) VALUES (1204, 'SOLOMON ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1204, 'SB', 1204, 1);
INSERT INTO text(id, default_value) VALUES (1205, 'SOMALIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1205, 'SO', 1205, 1);
INSERT INTO text(id, default_value) VALUES (1206, 'SOUTH AFRICA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1206, 'ZA', 1206, 1);
INSERT INTO text(id, default_value) VALUES (1207, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1207, 'GS', 1207, 1);
INSERT INTO text(id, default_value) VALUES (1208, 'SOUTH SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1208, 'SS', 1208, 1);
INSERT INTO text(id, default_value) VALUES (1209, 'SPAIN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1209, 'ES', 1209, 1);
INSERT INTO text(id, default_value) VALUES (1210, 'SRI LANKA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1210, 'LK', 1210, 1);
INSERT INTO text(id, default_value) VALUES (1211, 'SUDAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1211, 'SD', 1211, 1);
INSERT INTO text(id, default_value) VALUES (1212, 'SURINAME');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1212, 'SR', 1212, 1);
INSERT INTO text(id, default_value) VALUES (1213, 'SVALBARD AND JAN MAYEN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1213, 'SJ', 1213, 1);
INSERT INTO text(id, default_value) VALUES (1214, 'SWAZILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1214, 'SZ', 1214, 1);
INSERT INTO text(id, default_value) VALUES (1215, 'SWEDEN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1215, 'SE', 1215, 1);
INSERT INTO text(id, default_value) VALUES (1216, 'SWITZERLAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1216, 'CH', 1216, 1);
INSERT INTO text(id, default_value) VALUES (1217, 'SYRIAN ARAB REPUBLIC');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1217, 'SY', 1217, 1);
INSERT INTO text(id, default_value) VALUES (1218, 'TAIWAN, PROVINCE OF CHINA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1218, 'TW', 1218, 1);
INSERT INTO text(id, default_value) VALUES (1219, 'TAJIKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1219, 'TJ', 1219, 1);
INSERT INTO text(id, default_value) VALUES (1220, 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1220, 'TZ', 1220, 1);
INSERT INTO text(id, default_value) VALUES (1221, 'THAILAND');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1221, 'TH', 1221, 1);
INSERT INTO text(id, default_value) VALUES (1222, 'TIMOR-LESTE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1222, 'TL', 1222, 1);
INSERT INTO text(id, default_value) VALUES (1223, 'TOGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1223, 'TG', 1223, 1);
INSERT INTO text(id, default_value) VALUES (1224, 'TOKELAU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1224, 'TK', 1224, 1);
INSERT INTO text(id, default_value) VALUES (1225, 'TONGA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1225, 'TO', 1225, 1);
INSERT INTO text(id, default_value) VALUES (1226, 'TRINIDAD AND TOBAGO');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1226, 'TT', 1226, 1);
INSERT INTO text(id, default_value) VALUES (1227, 'TUNISIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1227, 'TN', 1227, 1);
INSERT INTO text(id, default_value) VALUES (1228, 'TURKEY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1228, 'TR', 1228, 1);
INSERT INTO text(id, default_value) VALUES (1229, 'TURKMENISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1229, 'TM', 1229, 1);
INSERT INTO text(id, default_value) VALUES (1230, 'TURKS AND CAICOS ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1230, 'TC', 1230, 1);
INSERT INTO text(id, default_value) VALUES (1231, 'TUVALU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1231, 'TV', 1231, 1);
INSERT INTO text(id, default_value) VALUES (1232, 'UGANDA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1232, 'UG', 1232, 1);
INSERT INTO text(id, default_value) VALUES (1233, 'UKRAINE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1233, 'UA', 1233, 1);
INSERT INTO text(id, default_value) VALUES (1234, 'UNITED ARAB EMIRATES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1234, 'AE', 1234, 1);
INSERT INTO text(id, default_value) VALUES (1235, 'UNITED KINGDOM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1235, 'GB', 1235, 1);
INSERT INTO text(id, default_value) VALUES (1236, 'UNITED STATES');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1236, 'US', 1236, 1);
INSERT INTO text(id, default_value) VALUES (1237, 'UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1237, 'UM', 1237, 1);
INSERT INTO text(id, default_value) VALUES (1238, 'URUGUAY');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1238, 'UY', 1238, 1);
INSERT INTO text(id, default_value) VALUES (1239, 'UZBEKISTAN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1239, 'UZ', 1239, 1);
INSERT INTO text(id, default_value) VALUES (1240, 'VANUATU');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1240, 'VU', 1240, 1);
INSERT INTO text(id, default_value) VALUES (1241, 'VENEZUELA, BOLIVARIAN REPUBLIC OF');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1241, 'VE', 1241, 1);
INSERT INTO text(id, default_value) VALUES (1242, 'VIET NAM');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1242, 'VN', 1242, 1);
INSERT INTO text(id, default_value) VALUES (1243, 'VIRGIN ISLANDS, BRITISH');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1243, 'VG', 1243, 1);
INSERT INTO text(id, default_value) VALUES (1244, 'VIRGIN ISLANDS, U.S.');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1244, 'VI', 1244, 1);
INSERT INTO text(id, default_value) VALUES (1245, 'WALLIS AND FUTUNA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1245, 'WF', 1245, 1);
INSERT INTO text(id, default_value) VALUES (1246, 'WESTERN SAHARA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1246, 'EH', 1246, 1);
INSERT INTO text(id, default_value) VALUES (1247, 'YEMEN');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1247, 'YE', 1247, 1);
INSERT INTO text(id, default_value) VALUES (1248, 'ZAMBIA');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1248, 'ZM', 1248, 1);
INSERT INTO text(id, default_value) VALUES (1249, 'ZIMBABWE');
INSERT INTO entity(id, code, text_id, entity_type_id) VALUES (1249, 'ZW', 1249, 1);

ALTER SEQUENCE entity_seq RESTART WITH 2000;
ALTER SEQUENCE text_seq RESTART WITH 2000;
